src/objects/Action__c.object
<CustomObject>
    <fields>
        <fullName>Activation_Type__c</fullName>
        <description>This means if action needs to perform automatically or manually</description>
        <label>Activation Type</label>
        <picklist>
            <picklistValues>
                <fullName>Automatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Task_Description__c</fullName>
        <description>Task detail(Name, Type, Subject, Description) will be saved in JSON format.</description>
        <label>Task Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Template_Id__c</fullName>
        <description>Save id of EmailTemplate (If Email Template), Call and SMS template data will be retrieved from RingDNA</description>
        <label>Template Id</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Template_Name__c</fullName>
        <label>Template Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call+Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Cadence__c.object
<CustomObject>
    <fields>
        <fullName>Participent_Activation__c</fullName>
        <label>Participent Activation</label>
        <picklist>
            <picklistValues>
                <fullName>Automatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <label>Record Type</label>
        <picklist>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Status</label>
        <type>Checkbox</type>
    </fields>
    <label>Sequence</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CadenceAction__c.object
<CustomObject>
    <fields>
        <fullName>Action_Id__c</fullName>
        <label>Action Id</label>
        <referenceTo>Action__c</referenceTo>
        <relationshipName>CadenceActions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cadence_Id__c</fullName>
        <label>Sequence Id</label>
        <referenceTo>Cadence__c</referenceTo>
        <relationshipName>CadenceActions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SequenceAction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SequenceActions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Cadence_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sequence ID</label>
        <referenceTo>Cadence__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>isActivated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isActivated</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Cadence_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sequence Id</label>
        <referenceTo>Cadence__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>isActivated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isActivated</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/ActionDetailViewCtrl.cls
public class ActionDetailViewCtrl {

	public class ActionDetailWrapper {
		@AuraEnabled public Action action;
		@AuraEnabled public List<ParticipantWrapper> participantList;
		@AuraEnabled public List<SequenceWrapper> cadWrapper; 
	}

	@AuraEnabled
	public static ActionDetailWrapper getActionData(Id actionId) {

		Action__c action = [Select Id, Name, Type__c, Task_Description__c, Template_Id__c, Template_Name__c, Activation_Type__c From Action__c where Id = :actionId]; 

		Action actionWrapper = New Action(action.Id, action.Activation_Type__c, action.Name, action.Task_Description__c,
				action.Template_Id__c, action.Template_Name__c, action.Type__c);
		ActionDetailWrapper actDetailWrap = new ActionDetailWrapper();
		actDetailWrap.action = actionWrapper;
		//Getting Sequences data 
		List<CadenceAction__c> cadenceActions = [Select Id, Cadence_Id__c from CadenceAction__c where Action_ID__c = :action.Id];
		Set<Id> cadenceIds = new Set<Id>();
		for(CadenceAction__c cadAction : cadenceActions) {
			cadenceIds.add(cadAction.Cadence_Id__c);
		}

		//Getting cadence wise participants
		Map<Id, Integer> cadenceWiseParticipants = CadenceActionListController.getCadenceWiseParticipants();

		List<Cadence__c> cadenceList = [Select Id, Name, Status__c, Record_Type__c, Participent_Activation__c From Cadence__c where Id IN : cadenceIds];
		List<SequenceWrapper> cadWrapList = new List<SequenceWrapper>();
		for(Cadence__c cad : cadenceList) {
			SequenceWrapper cadWrap = new SequenceWrapper();
			cadWrap.id = cad.Id;
			cadWrap.name = cad.Name;
			if(cad.Status__c) {
				cadWrap.status = 'Active';    
			} else {
				cadWrap.status = 'Inactive';
			}
			cadWrap.recordType = cad.Record_Type__c;
			cadWrap.activation = cad.Participent_Activation__c;
			cadWrap.participants = cadenceWiseParticipants.get(cad.Id);
			cadWrapList.add(cadWrap);
		}
		actDetailWrap.cadWrapper = new List<SequenceWrapper>();
		actDetailWrap.cadWrapper.addAll(cadWrapList);

		//Getting participants
		List<ParticipantWrapper> partWrapper = new List<ParticipantWrapper>();
		List<Lead> leadParticipants = [Select Id, Name, Priority__c, Company, Email, Phone, isActivated__c from Lead where IsConverted != true AND Cadence_ID__c IN :cadenceIds];
		List<Contact> contactParticipants = [Select Id, Name, Priority__c, Account.name, Account.Id, Email, Phone, isActivated__c from Contact where Cadence_ID__c IN :cadenceIds];

		for(Lead l : leadParticipants) {
			Integer priority = 0;
			if(l.Priority__c != null) {
				priority = (Integer)l.Priority__c;
			} 
			ParticipantWrapper partWrap = new ParticipantWrapper(l.Id ,l.Name, priority, l.Company, '' ,'Lead', l.Email, l.Phone, '', l.isActivated__c);
			partWrapper.add(partWrap);
		}        

		for(Contact cont : contactParticipants) {
			Integer priority = 0;
			if(cont.Priority__c != null) {
				priority = (Integer)cont.Priority__c;

			}
			ParticipantWrapper partWrap = new ParticipantWrapper(cont.Id, cont.Name, priority, cont.Account.name, cont.Account.Id, 'Contact', cont.Email, cont.Phone, '', cont.isActivated__c);
			partWrapper.add(partWrap);
		}        
		actDetailWrap.participantList = partWrapper;

		return actDetailWrap;
	}

	@AuraEnabled
	public static List<ParticipantWrapper> getCadenceParticipantsData(Id cadId) {

		if(cadId == null) {
			return null;
		}

		List<ParticipantWrapper> partWrapper = new List<ParticipantWrapper>();
		List<Lead> leadParticipants = [Select Id, Name, Company, Email, Phone, isActivated__c, Priority__c from Lead where IsConverted != true AND Cadence_ID__c = :cadId];
		List<Contact> contactParticipants = [Select Id, Name, Account.name, Account.Id, Email, Phone, isActivated__c, Priority__c from Contact where Cadence_ID__c = :cadId];

		for(Lead l : leadParticipants) {
			Integer priority = 0;
			if(l.Priority__c != null) {
				priority = (Integer)l.Priority__c;
			}
			ParticipantWrapper partWrap = new ParticipantWrapper(l.Id ,l.Name, priority, l.Company, '', 'Lead', l.Email, l.Phone, '', l.isActivated__c);
			partWrapper.add(partWrap);
		}        

		for(Contact cont : contactParticipants) {
			Integer priority = 0;
			if(cont.Priority__c != null) {
				priority = (Integer)cont.Priority__c;    
			}

			ParticipantWrapper partWrap = new ParticipantWrapper(cont.Id, cont.Name, priority, cont.Account.name, cont.Account.Id, 'Contact', cont.Email, cont.Phone, '', cont.isActivated__c);
			partWrapper.add(partWrap);
		}        
		return partWrapper;
	}

	@AuraEnabled
	public static void togglePartActivation(String selectedRows) {
		List<ParticipantWrapper> wrapList = (List<ParticipantWrapper>)JSON.deserialize(selectedRows, List<ParticipantWrapper>.class);
		List<sObject> participants = new List<sObject>();
		for(ParticipantWrapper partWrap : wrapList) {
			if(partWrap.objType.equalsIgnoreCase('Contact')) {
				Contact cont = new Contact(Id = partWrap.id);	
				cont.isActivated__c = partWrap.status.equalsIgnoreCase('Disabled');
				participants.add(cont);
			} else { 
				Lead l = new Lead(Id = partWrap.id);
				l.isActivated__c = partWrap.status.equalsIgnoreCase('Disabled');
				participants.add(l); 
			}
		}
		Database.SaveResult[] results = Database.update(participants, false);
	}

	public class SequenceWrapper {
		@AuraEnabled public Id id;
		@AuraEnabled public String name;
		@AuraEnabled public String activation;
		@AuraEnabled public String recordType;
		@AuraEnabled public String status;
		@AuraEnabled public Integer participants;
	}

	public class ParticipantWrapper {
		@AuraEnabled public Id id;
		@AuraEnabled public String name;
		@AuraEnabled public Integer priority;
		@AuraEnabled public String company;
		@AuraEnabled public String companyId;
		@AuraEnabled public String objType;
		@AuraEnabled public String email;
		@AuraEnabled public String phone;
		@AuraEnabled public String nextAction;
		@AuraEnabled public String status;

		public ParticipantWrapper(Id actionId, String name, Integer priority, String company, String companyId, String objType, String email, String phone, String nextAction, Boolean status) {
			this.id = actionId;
			this.name = name;     
			this.priority = priority;
			this.company = company;
			this.companyId = companyId;

			this.objType = objType;
			if(status) {
				this.status	= 'Active';
			} else {
				this.status = 'Disabled';
			}
			this.email = email;
			this.phone = phone;
			this.nextAction = nextAction;
		}

	}
}