src/objects/Action__c.object
<CustomObject>
    <fields>
        <fullName>Activation_Type__c</fullName>
        <description>This means if action needs to perform automatically or manually</description>
        <label>Activation Type</label>
        <picklist>
            <picklistValues>
                <fullName>Automatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Task_Description__c</fullName>
        <description>Task detail(Name, Type, Subject, Description) will be saved in JSON format.</description>
        <label>Task Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Template_Id__c</fullName>
        <description>Save id of EmailTemplate (If Email Template), Call and SMS template data will be retrieved from RingDNA</description>
        <label>Template Id</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Template_Name__c</fullName>
        <label>Template Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call+Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DynamicActionDetailsController.cls
public class DynamicActionDetailsController {
	public static String nameSpace = CadenceConstants.NAMESPACE;
	public static String TASK_OBJECT_STRING = 'Task';

	@AuraEnabled
	public static ActionDetailController.ActionWrapper getActionWrapper() {
		ActionDetailController.ActionWrapper initActionObj = new ActionDetailController.ActionWrapper();
		initActionObj.listEmailTemplate = CadenceService.getEmailTemplates();
		if(!test.isRunningTest()){
			initActionObj.listSmsTemplate = CadenceService.getSMSTemplates();
			initActionObj.listCallTemplate = CadenceService.getCallTemplates();
			initActionObj.listVMTemplate = CadenceService.getVMTemplates();
		}
		initActionObj.wrapperTaskFields = CadenceService.getFields(TASK_OBJECT_STRING);
		initActionObj.action = new Action();
		return initActionObj; 
	}

	@AuraEnabled
	public static Id saveAction(string actWra, Task taskObj) {
		Action action = (Action)System.JSON.deserialize(actWra, Action.class); 
		if (action.type == TASK_OBJECT_STRING){
			Task taskObjToCreateJson = taskObj;
			action.taskDescription = JSON.serialize(taskObjToCreateJson);
		}
		Action__c act = ActionDetailController.getAction(action);
		upsert act;
		return act.id;
	}

	@AuraEnabled
	public static ActionDetailController.ActionDataWrapper getActionData(Id actionId) {
		ActionDetailController.ActionDataWrapper actionDataWrapper = new ActionDetailController.ActionDataWrapper();
		Action__c action = [Select Id, Name, Activation_Type__c, Task_Description__c, Template_Id__c, Template_Name__c, Type__c From Action__c where Id = :actionId];
		Action actionCls = New Action(action.Id, action.Activation_Type__c, action.Name, action.Task_Description__c,
				action.Template_Id__c, action.Template_Name__c, action.Type__c);
		actionDataWrapper.actionCls = actionCls;	
		if((action.Task_Description__c != null) && action.Task_Description__c != '') {
			Map<String, Object> taskObjs = (Map<String, Object>)JSON.deserializeUntyped(action.Task_Description__c);
			taskObjs.remove('attributes');
			List<ActionDetailController.wrapperTaskField> wrapperTaskFieldObjs = new List<ActionDetailController.wrapperTaskField>();
			for(String key : taskObjs.keySet()) {
				ActionDetailController.wrapperTaskField wrapperTaskFieldObj = new ActionDetailController.wrapperTaskField();
				wrapperTaskFieldObj.key = key;
				wrapperTaskFieldObj.value = String.valueOf(taskObjs.get(key));
				wrapperTaskFieldObjs.add(wrapperTaskFieldObj);
			}
			actionDataWrapper.taskList = wrapperTaskFieldObjs;              
		}
		return actionDataWrapper;
	}

	@AuraEnabled
	public static Action getActionById(Id actionId) {
		Action__c action = [Select Id, Name, Activation_Type__c, Task_Description__c, Template_Id__c, 
		                    Template_Name__c, Type__c From Action__c where Id = :actionId];
		Action actionCls = New Action(action.Id, action.Activation_Type__c, action.Name, action.Task_Description__c,
				action.Template_Id__c, action.Template_Name__c, action.Type__c);
		return actionCls;
	}
}