src/objects/Action__c.object
<CustomObject>
    <fields>
        <fullName>Activation_Type__c</fullName>
        <description>This means if action needs to perform automatically or manually</description>
        <label>Activation Type</label>
        <picklist>
            <picklistValues>
                <fullName>Automatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email_Type__c</fullName>
        <label>Email Type</label>
		<picklist>
            <picklistValues>
                <fullName>SFDC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIVE</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Task_Description__c</fullName>
        <description>Task detail(Name, Type, Subject, Description) will be saved in JSON format.</description>
        <label>Task Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Template_Id__c</fullName>
        <description>Save id of EmailTemplate (If Email Template), Call and SMS template data will be retrieved from RingDNA</description>
        <label>Template Id</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call+Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Cadence__c.object
<CustomObject>
    <fields>
        <fullName>Entrance_Criteria_PE__c</fullName>
        <description>JSON Format (internal purpose)</description>
        <label>Entrance Criteria PE</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entrance_Criteria__c</fullName>
        <description>JSON Format</description>
        <label>Entrance Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Exit_Criteria_PE__c</fullName>
        <label>Exit Criteria PE</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exit_Criteria__c</fullName>
        <label>Exit Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Participent_Activation__c</fullName>
        <label>Participent Activation</label>
        <picklist>
            <picklistValues>
                <fullName>Automatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <label>Record Type</label>
        <picklist>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>matching_priority__c</fullName>
        <label>matching priority</label>
        <picklist>
            <picklistValues>
                <fullName>P1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P5</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sequence</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CadenceAction__c.object
<CustomObject>
    <fields>
        <fullName>Action_Criteria_PE__c</fullName>
        <label>Action Criteria PE</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Action_Criterion__c</fullName>
        <label>Action Criterion</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Action_Id__c</fullName>
        <label>Action Id</label>
        <referenceTo>Action__c</referenceTo>
        <relationshipName>CadenceActions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cadence_Id__c</fullName>
        <label>Sequence Id</label>
        <referenceTo>Cadence__c</referenceTo>
        <relationshipName>CadenceActions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Day__c</fullName>
        <label>Day</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fields_To_Update_Action__c</fullName>
        <description>It would keep the information of field to update in JSON format.</description>
        <label>Fields To Update Action</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Hour__c</fullName>
        <label>Hour</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <description>Index for sequence Action Detail page.</description>
        <label>Index</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Trigger_Type__c</fullName>
        <label>Trigger Type</label>
        <picklist>
            <picklistValues>
                <fullName>Immediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Time Based</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hours</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SequenceAction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SequenceActions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Cadence_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sequence ID</label>
        <referenceTo>Cadence__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
	<fields>
		<fullName>Opportunity_Id__c</fullName>
		<label>Opportunity Id</label>
		<length>20</length>
		<type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Cadence_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sequence Id</label>
        <referenceTo>Cadence__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Sequence_Action__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Execution_Date__c</fullName>
        <label>Actual Execution Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CadenceAction_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Action ID</label>
        <referenceTo>CadenceAction__c</referenceTo>
        <relationshipLabel>Sequence Actions</relationshipLabel>
        <relationshipName>Sequence_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cadence_Type__c</fullName>
        <formula>TEXT( CadenceAction_ID__r.Cadence_Id__r.Record_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sequence Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Id</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sequence Actions</relationshipLabel>
        <relationshipName>Sequence_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expected_Execution_Date__c</fullName>
        <label>Expected Execution Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lead_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Id</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Sequence Actions</relationshipLabel>
        <relationshipName>Sequence_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show_on_Target_List__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Show on Today</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isActionPerformed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isActionPerformed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isDeferred__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isDeferred</label>
        <type>Checkbox</type>
    </fields>
    <label>Sequence Action</label>
    <nameField>
        <label>Sequence Actions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequence Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SequenceEngineHelper.cls
public class SequenceEngineHelper {
    
    public static Map<Id, Set<Id>> getSequenceHistory()
    {
    	Map<Id, Set<Id>> participantIdToSequenceIdSetMap;
    	
    	return participantIdToSequenceIdSetMap;
    } 
    
    public static List<SObject> unAssociateParticipants(List<SObject> participantList)
    {
    	return participantList;
    }
    
    public static void deleteUnPerformedParticipantActions(List<SObject> participantList)
    {
    	 
    }
    
    public static List<SObject> removeChildListItemsFromParentList(List<SObject> parentList, List<Sobject> childList)
    {    	
    	for(Integer index = 0; index < childList.size(); index++)
    	{
		   if(parentList.contains(childList.get(index)))
    		{
    		   parentList.remove(index);
    		}
    	}    	
    	return parentList; 	
    }    
    
    public static Map<Id, Cadence__c> getSequenceMap(List<string> participantType)
    {
    	return new Map<Id, Cadence__c>([SELECT Id, Name, Entrance_Criteria__c, Entrance_Criteria_PE__c, Exit_Criteria__c, Exit_Criteria_PE__c,
                                       Participent_Activation__c, Record_Type__c, Status__c, matching_priority__c, CreatedDate,LastModifiedDate,
                                       (SELECT Id, Name, Action_Criterion__c, Action_Criteria_PE__c, Action_Id__c,
                                        Cadence_Id__c, Day__c, Hour__c, Trigger_Type__c, Fields_To_Update_Action__c, Action_Id__r.Activation_Type__c, 
                                        Action_Id__r.Task_Description__c, Action_Id__r.Template_Id__c, Action_Id__r.Type__c  
                                        FROM CadenceActions__r order by Index__c) 
                                       FROM Cadence__c WHERE Status__c = true AND Record_Type__c in : participantType]);
    }
    
    /**
    * Name: getParticipantListToCreateParticipantActions
    * Desc: Method to get participant list for which Participant Actions are not created 
    * @param:  (1) participantList - List<SObject> - List of Contact or Lead records
    * 		   (2) sequenceIdToSequenceMap - Map<Id, Cadence__c> - sequence Id to Sequence record (with sequence actions) list map
    * 		   (3) participantType - String - object Type (Lead/Contact)
    * @return: List<SObject> - participant list for which Participant Actions are not created
    **/
    public static List<SObject> getParticipantListToCreateParticipantActions(List<SObject> participantList, Map<Id, Cadence__c> sequenceIdToSequenceMap, 
    																					String participantType) {
	   	Map<Id,Set<Id>> participantIdToSequenceActionIdSetMap = getParticipantIdToSequenceActionIdSetMap(participantList);
	   	Map<Id, Set<Id>> sequenceIdToSequenceActionIdSetMap = new Map<Id, Set<Id>>();
	   	for(Id sequenceId : sequenceIdToSequenceMap.keySet()) {
	   		if(sequenceIdToSequenceMap.get(sequenceId).CadenceActions__r != null) {
	   			sequenceIdToSequenceActionIdSetMap.put(sequenceId, new Set<Id>());
	   			for(CadenceAction__c sequenceAction : sequenceIdToSequenceMap.get(sequenceId).CadenceActions__r) {
	   				sequenceIdToSequenceActionIdSetMap.get(sequenceId).add(sequenceAction.Id);
	   			}
	   		}
	   	}
	   	
	   	List<SObject> requiredParticipantList = new List<SObject>();
	   	for(SObject participant: participantList) {
	   		Set<Id> participantSequenceActionIdSet = participantIdToSequenceActionIdSetMap.containsKey(participant.Id) ? participantIdToSequenceActionIdSetMap.get(participant.Id) 
	   												: new Set<Id>();
	   		Set<Id> SequenceActionIdSet;
	   		 
	   		if(participantType == 'Contact') {
	   			Contact contactRecord = (Contact)participant;
	   			SequenceActionIdSet = sequenceIdToSequenceActionIdSetMap.containsKey(contactRecord.Cadence_ID__c) ? sequenceIdToSequenceActionIdSetMap.get(contactRecord.Cadence_ID__c)
	   									: new Set<Id>(); 
	   		} else {
	   			Lead leadRecord = (Lead)participant;
	   			SequenceActionIdSet = sequenceIdToSequenceActionIdSetMap.containsKey(leadRecord.Cadence_ID__c) ? sequenceIdToSequenceActionIdSetMap.get(leadRecord.Cadence_ID__c)
	   									: new Set<Id>(); 
	   		}
	   		
   			if(!participantSequenceActionIdSet.equals(SequenceActionIdSet)) {
   				requiredParticipantList.add(participant);
   			}
	   	}
	   	return requiredParticipantList;
	}
	
	
    /**
    * Name: getParticipantIdToSequenceActionIdSetMap
    * Desc: Method to get participant id and related Participant action's parent sequence action's id set 
    * @param:  (1) participantList - List<SObject> - List of Contact or Lead records
    * @return: Map<Id,Set<Id>> - participant Id To Participant action's parent sequence action's id set Map
    **/
    private static Map<Id,Set<Id>> getParticipantIdToSequenceActionIdSetMap(List<SObject> participantList) {
	   	Map<Id,Set<Id>> participantIdToSequenceActionIdSetMap = new Map<Id,Set<Id>>();
	   	List<Sequence_Action__c> participantActions = [SELECT Contact_Id__c, Lead_Id__c, CadenceAction_ID__c FROM Sequence_Action__c 
	   										WHERE Contact_Id__c IN: participantList OR Lead_Id__c IN: participantList];
	   	
	   	Id participantId = null;
	   	
	   	for(Sequence_Action__c participantAction :participantActions) {
	   		participantId = (String.isNotBlank(participantAction.Contact_Id__c)) ? participantAction.Contact_Id__c : 
	   							(String.isNotBlank(participantAction.Lead_Id__c) ? participantAction.Lead_Id__c : null); 
	   	
		    if(participantId != null ) {
		    	if(!participantIdToSequenceActionIdSetMap.containsKey(participantId)) {
			    	participantIdToSequenceActionIdSetMap.put(participantId, new Set<Id>());
			   	} 
		    	participantIdToSequenceActionIdSetMap.get(participantId).add(participantAction.CadenceAction_ID__c);
		    }
	   	}
	   	return participantIdToSequenceActionIdSetMap;
	}
	
	public static Map<Id, List<Sequence_Action__c>> getRemainingParticipantAction(List<SObject> participantList, String participantType) 
	{	    
	    Map<Id, SObject> participantMap = new Map<Id, SObject>(participantList);
	    
	    Set<Id> participantIds = participantMap.keySet();
	    
	    Map<Id, List<Sequence_Action__c>> participantIdToSequenceActionsList = new Map<Id, List<Sequence_Action__c>>();
        
        //Getting all the available and unperformed action for object
        List<Sequence_Action__c> participantActions = new List<Sequence_Action__c>();            
        
        participantActions = [Select Id, Name, CadenceAction_ID__c, Show_on_Target_List__c, Lead_Id__c, Contact_Id__c,Opportunity_Id__c,Cadence_Type__c, isActionPerformed__c, CadenceAction_Id__r.Day__c,
                                  CadenceAction_Id__r.Hour__c, CadenceAction_Id__r.Action_Id__r.Type__c, CadenceAction_Id__r.Fields_To_Update_Action__c,
                                  CadenceAction_Id__r.Action_Id__r.Activation_Type__c, CadenceAction_Id__r.Trigger_Type__c, CadenceAction_Id__r.Action_Id__r.Email_Type__c,
                                  CadenceAction_Id__r.Action_Id__r.Task_Description__c, CadenceAction_Id__r.Action_Id__r.Template_Id__c, 
                                  CadenceAction_Id__r.Index__c, Expected_Execution_Date__c, Actual_Execution_Date__c From Sequence_Action__c 
                                  where (Lead_Id__c IN :participantIds OR Contact_Id__c IN : participantIds) AND CadenceAction_ID__r.Cadence_Id__r.Record_Type__c = : participantType AND isActionPerformed__c = false AND isDeferred__c = false 
                                  order by CadenceAction_Id__r.Index__c];
       
        for(Sequence_Action__c participantAction : participantActions) {
            if(participantAction.Lead_Id__c == null && participantAction.Contact_Id__c == null) {
                continue;
            }
			
            if(participantAction.Lead_Id__c == null) {
                if(!participantIdToSequenceActionsList.containsKey(participantAction.Contact_Id__c)) {
                    participantIdToSequenceActionsList.put(participantAction.Contact_Id__c, new List<Sequence_Action__c>{participantAction});	    
                } else {
                    participantIdToSequenceActionsList.get(participantAction.Contact_Id__c).add(participantAction);
                }	    
            } else {
                if(!participantIdToSequenceActionsList.containsKey(participantAction.Lead_Id__c)) {
                    participantIdToSequenceActionsList.put(participantAction.Lead_Id__c, new List<Sequence_Action__c>{participantAction});    
                } else {
                    participantIdToSequenceActionsList.get(participantAction.Lead_Id__c).add(participantAction);
                }
            }
        }
        return participantIdToSequenceActionsList;
	}
}