src/objects/Action__c.object
<CustomObject>
    <fields>
        <fullName>Activation_Type__c</fullName>
        <description>This means if action needs to perform automatically or manually</description>
        <label>Activation Type</label>
        <picklist>
            <picklistValues>
                <fullName>Automatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email_Type__c</fullName>
        <label>Email Type</label>
		<picklist>
            <picklistValues>
                <fullName>SFDC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NATIVE</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Template_Id__c</fullName>
        <description>Save id of EmailTemplate (If Email Template), Call and SMS template data will be retrieved from RingDNA</description>
        <label>Template Id</label>
        <type>TextArea</type>
    </fields>
    <label>Action</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Cadence__c.object
<CustomObject>
    <fields>
        <fullName>Entrance_Criteria__c</fullName>
        <description>JSON Format</description>
        <label>Entrance Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Exit_Criteria__c</fullName>
        <label>Exit Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Participent_Activation__c</fullName>
        <label>Participent Activation</label>
        <picklist>
            <picklistValues>
                <fullName>Automatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>matching_priority__c</fullName>
        <label>matching priority</label>
        <picklist>
            <picklistValues>
                <fullName>P1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P5</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sequence</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CadenceAction__c.object
<CustomObject>
    <label>SequenceAction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SequenceActions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sequence_Action__c.object
<CustomObject>
    <fields>
        <fullName>CadenceAction_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Action ID</label>
        <referenceTo>CadenceAction__c</referenceTo>
        <relationshipLabel>Sequence Actions</relationshipLabel>
        <relationshipName>Sequence_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Id</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Sequence Actions</relationshipLabel>
        <relationshipName>Sequence_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sequence Action</label>
    <nameField>
        <label>Sequence Actions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequence Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NativeEmailControllerTest.cls
@isTest
public class NativeEmailControllerTest {
	public static Action__c action;
	public static EmailTemplate template;
	public static Lead testLead;
	public static String subject,body;
	public static Cadence__c cadenceLead;
	public static CadenceAction__c cadenceActionLead;
	public static Sequence_Action__c sequenceActionLead;
	static{
		//create action of type email
		action = TestDataFactory.createAction('Email');
		//creation of email template
		System.runAs ( new User(Id = UserInfo.getUserId()) ) {
			EmailTemplate validEmailTemplate = new EmailTemplate();
			validEmailTemplate.isActive = true;
			validEmailTemplate.Name = 'name';
			validEmailTemplate.DeveloperName = 'unique_name';
			validEmailTemplate.TemplateType = 'text';
			validEmailTemplate.Body='Test Body for {!Lead.Name}';
			validEmailTemplate.Subject='New {!Lead.Name}';
			validEmailTemplate.FolderId = UserInfo.getUserId();
			insert validEmailTemplate;
			template=validEmailTemplate;
			action.Template_Id__c= validEmailTemplate.id;
		}
		action.Activation_Type__c='Manual';
		action.Email_Type__c='NATIVE';
		insert action;
		//creation of cadence of type Lead
		cadenceLead = TestDataFactory.createCadence('Lead');
		Criterion c1 = TestDataFactory.createCriterion(1, 'FirstName', 'STRING', 'equals', 'Test');
		String jsonEntryString = TestDataFactory.createCadenceJSON(new List<Criterion>{c1}, CadenceConstants.CONDITION_OR, null);
		Criterion exitCriteria = TestDataFactory.createCriterion(1, 'Email', 'STRING', 'equals', 'test123@gmail.com');
		String jsonExitString = TestDataFactory.createCadenceJSON(new List<Criterion>{exitCriteria}, CadenceConstants.CONDITION_AND, null);
		cadenceLead.Entrance_Criteria__c = jsonEntryString;
		cadenceLead.Participent_Activation__c='Automatic';
		cadenceLead.matching_priority__c='P1';
		cadenceLead.Exit_Criteria__c = jsonExitString; 
		insert cadenceLead;
		//craetion of Cadence Action
		cadenceActionLead = TestDataFactory.createCadenceAction(cadenceLead.Id, action.Id);
		insert cadenceActionLead;
		//test lead which satisfy entrance criteria
		testLead = TestDataFactory.createLead(cadenceLead.Id);
		testLead.FirstName='Test';
		testLead.LastName='Lead';
		testLead.Company='Test Company';
		testLead.Email='test@gmail.com';
		insert testLead;
		sequenceActionLead=new Sequence_Action__c(CadenceAction_Id__c=cadenceActionLead.Id,Lead_Id__c=testLead.Id);
		insert sequenceActionLead;
	} 
	@isTest
	public static void testGetData(){
		Test.startTest();
		NativeEmailController.NativeEmailWrapper emailWrapper=NativeEmailController.getData(testLead.Id,template.Id);
		Test.stopTest();
		System.assertEquals('New Test Lead',emailWrapper.emailTemplateSubject);
		subject=emailWrapper.emailTemplateSubject;
		System.assertEquals('Test Body for Test Lead',emailWrapper.emailTemplateBody);
		body=emailWrapper.emailTemplateBody;
	}
	@isTest
	public static void testResolveMergeFields(){
		NativeEmailMessage message;
		Test.startTest();
		message=NativeEmailController.resolveMergeFields(testLead.Id,template.Id);
		Test.stopTest();
		System.assertEquals('New Test Lead',message.Subject);
		System.assertEquals('Test Body for Test Lead',message.Body);
	}

	@isTest
	public static void testSendEmail(){
		NativeEmailController.SendNativeEmailResult result = new NativeEmailController.SendNativeEmailResult();
		Test.startTest(); 
		result =NativeEmailController.sendEmail((String)testLead.Id,null,null,'Test Subject','test this body',(String)testLead.Id,(String)template.Id,(String)sequenceActionLead.Id);
		Test.stopTest();
		System.assertEquals(true, result.Success);
	}
}