src/objects/Action__c.object
<CustomObject>
    <label>Action</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Cadence__c.object
<CustomObject>
    <fields>
        <fullName>Entrance_Criteria__c</fullName>
        <description>JSON Format</description>
        <label>Entrance Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Exit_Criteria__c</fullName>
        <label>Exit Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Participent_Activation__c</fullName>
        <label>Participent Activation</label>
        <picklist>
            <picklistValues>
                <fullName>Automatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <label>Record Type</label>
        <picklist>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>matching_priority__c</fullName>
        <label>matching priority</label>
        <picklist>
            <picklistValues>
                <fullName>P1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P5</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sequence</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CadenceAction__c.object
<CustomObject>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Trigger_Type__c</fullName>
        <label>Trigger Type</label>
        <picklist>
            <picklistValues>
                <fullName>Immediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Time Based</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hours</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SequenceAction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SequenceActions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Sequence_Action__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Id</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sequence Actions</relationshipLabel>
        <relationshipName>Sequence_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Id</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Sequence Actions</relationshipLabel>
        <relationshipName>Sequence_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isActionPerformed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isActionPerformed</label>
        <type>Checkbox</type>
    </fields>
    <label>Sequence Action</label>
    <nameField>
        <label>Sequence Actions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequence Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LeadsTest.cls
@isTest
public class LeadsTest {

	public static Lead testLead;
	public static Cadence__c cadenceLead;
	public static Action__c actionCall;
	public static Action__c actionSMS;
	public static CadenceAction__c cadenceActionLeadCall;
	public static CadenceAction__c cadenceActionLeadSMS;
	public static final String CUSTOM_LOGIC = '1 AND (2 AND 3)';
	//Constants 
	public static Final String ACTION_TYPE_CALL = 'Call';
	public static Final String ACTION_TYPE_SMS = 'SMS';
	static{
		actionCall = TestDataFactory.createAction(ACTION_TYPE_CALL);
		insert actionCall;
		actionSMS = TestDataFactory.createAction(ACTION_TYPE_SMS);
		insert actionSMS;
		cadenceLead = TestDataFactory.createCadence('Lead');
		cadenceLead.Name='Lead Cadence';
		cadenceLead.Participent_Activation__c='Automatic';
		Criterion entry1 = TestDataFactory.createCriterion(1, 'FirstName', 'STRING', 'equals', 'Test');
		Criterion entry2 = TestDataFactory.createCriterion(2, 'LastName', 'STRING', 'equals', 'Test');
		String jsonEntryString = TestDataFactory.createCadenceJSON(new List<Criterion>{entry1,entry2}, CadenceConstants.CONDITION_AND, null);
		Criterion exitCriteria = TestDataFactory.createCriterion(1, 'Email', 'STRING', 'equals', 'test@gmail.com');
		String jsonExitString = TestDataFactory.createCadenceJSON(new List<Criterion>{exitCriteria}, CadenceConstants.CONDITION_AND, null);
		cadenceLead.Entrance_Criteria__c = jsonEntryString;
		cadenceLead.Status__c = false;
		cadenceLead.matching_priority__c='P1';
		cadenceLead.Exit_Criteria__c = jsonExitString;
		cadenceActionLeadCall = TestDataFactory.createCadenceAction(cadenceLead.Id, actionCall.Id);
		cadenceActionLeadCall.Trigger_Type__c='Immediate';
		cadenceActionLeadSMS = TestDataFactory.createCadenceAction(cadenceLead.Id, actionSMS.Id);
		cadenceActionLeadSMS.Trigger_Type__c='Immediate';
		testLead=new Lead(FirstName='Test',LastName='Test',Company='Test Company', Status='Open - Not Contacted',Priority__c=3);
		insert testLead;
	}
	@isTest
	public static void onAfterUpdate(){
		Sequence sequenceLead = TestDataFactory.createSequence(cadenceLead);
		SequenceAction sequenceActionLeadCall= TestDataFactory.createSequenceAction(cadenceActionLeadCall);
		SequenceAction sequenceActionLeadSMS= TestDataFactory.createSequenceAction(cadenceActionLeadSMS);
		//Test saveCadence
		CadenceProgressIndicatorController.saveCadence(system.JSON.serialize(sequenceLead), system.JSON.serialize(new List<SequenceAction> {sequenceActionLeadCall,sequenceActionLeadSMS}), New List<String>());
		//To get inserted cadence
		cadenceLead=[SELECT Id, Record_Type__c FROM Cadence__c WHERE Name='Lead Cadence' LIMIT 1];
		//To activate cadence
		CadenceController.activateCadence(cadenceLead.Id);
		List<Sequence_Action__c> sequenceActions=[SELECT Id, isActionPerformed__c FROM Sequence_Action__c WHERE Lead_Id__c=:testLead.Id];
		for(Sequence_Action__c sequenceAction:sequenceActions){
			sequenceAction.isActionPerformed__c=True;
		}
		update sequenceActions;
		Test.startTest();
		Database.LeadConvert leadConvert = new Database.LeadConvert();
		leadConvert.setLeadId(testLead.id);
		LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
		leadConvert.setConvertedStatus(convertStatus.MasterLabel);
		Database.LeadConvertResult result = Database.convertLead(leadConvert);
		Test.stopTest();
		System.assert(result.isSuccess());
		List<Sequence_Action__c> contactSequenceActions=[SELECT Id FROM Sequence_Action__c WHERE Contact_Id__c!=null];
		System.assertEquals(2, contactSequenceActions.size());
	}
}