src/objects/Cadence__c.object
<CustomObject>
    <label>Sequence</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Cadence_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sequence Id</label>
        <referenceTo>Cadence__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/LeadSelector.cls
public class LeadSelector {
    
    public static List<SObject> getLeadsWithMatchingExitCriteria(string participantType, List<SObject> participnatList, Map<Id, Cadence__c> sequenceMap, List<string> participantTypeAndParantGroupsList)
    {
    	List<SObject> ParticipantListWithMatchingCriteria = new List<SObject>();
    	
    	For(SObject participant : participnatList)
    	{
    		Lead objLead = (Lead)participant;
    		Cadence__c sequence =  sequenceMap.get(objLead.Cadence_Id__c);    		
    		//return SObject if exit criteria matches otherwise sends null
    		SObject matchedCriteria = RuleCriterionMatcher.matchExitCriterion(sequence, participant, participant, participantType); //--to do  //check how to convert the participantTypeAndParantGroupsList to SObject and pass as third argument
    		If(matchedCriteria != null)
    		{
    			ParticipantListWithMatchingCriteria.add(participant);
    		}    		
    	}    	
    	return ParticipantListWithMatchingCriteria; 
    }
}