src/objects/Cadence__c.object
<CustomObject>
    <fields>
        <fullName>Participent_Activation__c</fullName>
        <label>Participent Activation</label>
        <picklist>
            <picklistValues>
                <fullName>Automatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <label>Record Type</label>
        <picklist>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Status</label>
        <type>Checkbox</type>
    </fields>
    <label>Sequence</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CadenceBatchTest.cls
@isTest
private with sharing class CadenceBatchTest {
    Public static Final String RECORD_TYPE_CONTACT = 'Contact';
    
   @isTest
    private static void CadenceBatchTest(){
        Cadence__c cad = TestDataFactory.createCadence(RECORD_TYPE_CONTACT);
        cad.Name='contact';
        cad.Status__c=true;
        cad.Record_Type__c='Contact';
        cad.Participent_Activation__c='Automatic';
        insert cad; 
        Test.startTest();
        CadenceBatch cb= new CadenceBatch(cad.Id);
        Test.stopTest();
        
            }
    @isTest
    static void startdemoTest(){
       // Database.BatchableContext bc = new Database.BatchableContext();
        Test.startTest();
      //CadenceBatch.start(Database.BatchableContext bc);
        Test.stopTest();
    }

}