src/objects/Cadence__c.object
<CustomObject>
    <fields>
        <fullName>Entrance_Criteria__c</fullName>
        <description>JSON Format</description>
        <label>Entrance Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Exit_Criteria__c</fullName>
        <label>Exit Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Participent_Activation__c</fullName>
        <label>Participent Activation</label>
        <picklist>
            <picklistValues>
                <fullName>Automatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <label>Record Type</label>
        <picklist>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Participants__c</fullName>
        <label>Total Participants</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>matching_priority__c</fullName>
        <label>matching priority</label>
        <picklist>
            <picklistValues>
                <fullName>P1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P5</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sequence</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CadenceAction__c.object
<CustomObject>
    <fields>
        <fullName>Action_Criterion__c</fullName>
        <label>Action Criterion</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Action_Id__c</fullName>
        <label>Action Id</label>
        <referenceTo>Action__c</referenceTo>
        <relationshipName>CadenceActions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cadence_Id__c</fullName>
        <label>Sequence Id</label>
        <referenceTo>Cadence__c</referenceTo>
        <relationshipName>CadenceActions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Day__c</fullName>
        <label>Day</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fields_To_Update_Action__c</fullName>
        <description>It would keep the information of field to update in JSON format.</description>
        <label>Fields To Update Action</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Hour__c</fullName>
        <label>Hour</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Trigger_Type__c</fullName>
        <label>Trigger Type</label>
        <picklist>
            <picklistValues>
                <fullName>Immediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Time Based</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hours</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SequenceAction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SequenceActions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CadenceController.cls
public with sharing class CadenceController {
    
    @AuraEnabled
    public static cadenceDataWrapper getCadenceData(Id cadenceId){
        cadenceDataWrapper adWObj = new cadenceDataWrapper();
        adWObj.cObj  = CadenceController.getCadenceDetail(cadenceId);
        adWObj.conCriList = CadenceController.getFields(CadenceConstants.CONTACT_OBJECT_NAME);
        adWObj.ldCriList = CadenceController.getFields(CadenceConstants.LEAD_OBJECT_NAME);
        return adWObj;
    }
    @AuraEnabled
    public static cadenceDataWrapper getObjCriList(){
        cadenceDataWrapper adWObj = new cadenceDataWrapper();
        adWObj.conCriList = CadenceController.getFields(CadenceConstants.CONTACT_OBJECT_NAME);
        adWObj.ldCriList = CadenceController.getFields(CadenceConstants.LEAD_OBJECT_NAME);
        return adWObj;
    }
    
    public class cadenceDataWrapper{
        @AuraEnabled public Cadence__c cObj;
        @AuraEnabled public List<Criterion>  conCriList;
        @AuraEnabled public List<Criterion>  ldCriList;
    }
    
    
    @AuraEnabled
    public static Cadence__c getCadenceDetail(Id cadenceId){
    	List<Cadence__c> cadence = [Select Id, Name, Entrance_Criteria__c, Exit_Criteria__c, 
    	Participent_Activation__c, Record_Type__c, Matching_Priority__c ,
    	Status__c, Total_Participants__c,
    	(
    		Select id, name , Cadence_Id__c, Action_Id__c, Fields_To_Update_Action__c, Hour__c, Day__c, Trigger_Type__c, Action_Criterion__c from 
			CadenceActions__r
		)
    	from Cadence__c where Id=: cadenceId];
    	return cadence[0];								
    }
    
    @AuraEnabled
    public static List<Criterion> getFields(String objectStr){
    	List<Criterion> criterions = CadenceService.getFieldsWithLabels(objectStr);
    	return CadenceService.getFieldsWithLabels(objectStr);
    }
    
    @AuraEnabled
    public static void activateCadence(Id cadId) {
    	Cadence__c cad = new Cadence__c(Id=cadId, Status__c=true);
    	upsert cad;
    	updateParticipants(cadId); 
    	CadenceService.setParticipantsActivation(cadId, true);
    }
    
    @AuraEnabled
    public static void updateParticipants(Id cadId) {
    	CadenceBatch cadBatch = new CadenceBatch(cadId);
    	Database.executeBatch(cadBatch);
    }
    
    @AuraEnabled
    public static void deactivateCadence(Id cadId) {
    	Cadence__c cad = new Cadence__c(Id=cadId, Status__c=false);
    	upsert cad;
    	CadenceService.setParticipantsActivation(cadId, false);
    }
    
}