src/objects/Cadence__c.object
<CustomObject>
    <fields>
        <fullName>Record_Type__c</fullName>
        <label>Record Type</label>
        <picklist>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sequence</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CadenceBatch.cls
public with sharing class CadenceBatch implements Database.Batchable<sObject>, Database.stateful {

	public Cadence__c cadence;
	public String objName;
	public static String nameSpace = CadenceConstants.NAMESPACE;

	public CadenceBatch(Id cadID) {
		cadence = CadenceSelector.getCadenceById(cadId); 
		this.objName = cadence.Record_Type__c;
	}

	public Database.QueryLocator start(Database.BatchableContext bc) {
		String query = formQuery(objName);
		return Database.getQueryLocator(query);
	}

	public void execute(Database.BatchableContext bc, List<sObject> scope) {
		RuleCriterionMatcher.participantsList = scope;
	}

	public void finish(Database.BatchableContext bc) {

	}

	private String formQuery(String objName){

		Set<String> allowedFields = new Set<String>();
		String query = 'Select ';

		Map<String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get(objName).getDescribe().fields.getMap();
		for (Schema.SObjectField field : fieldMap.values()) {
			Schema.DescribeFieldResult fieldDescribe = field.getDescribe();
			if (!fieldDescribe.isAccessible()) {
				continue; 
			}
			String fieldName = fieldDescribe.getName();
			allowedFields.add(fieldName);
		}

		if(allowedFields.size() > 0 && nameSpace != ''){
			String apiNameWithNamespace;
			for(String fld : allowedFields){
				apiNameWithNamespace = nameSpace + fld;
				if(allowedFields.contains(apiNameWithNamespace)){
					allowedFields.remove(fld); 
				}
			}
		}

		query += String.join(new List<String>(allowedFields), ',');
		query += ' FROM '+ objName +' WHERE '+nameSpace+'Cadence_Id__c = null';

		return query;
	} 

}