src/objects/Cadence__c.object
<CustomObject>
    <fields>
        <fullName>Participent_Activation__c</fullName>
        <label>Participent Activation</label>
        <picklist>
            <picklistValues>
                <fullName>Automatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>matching_priority__c</fullName>
        <label>matching priority</label>
        <picklist>
            <picklistValues>
                <fullName>P1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P5</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sequence</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CadenceDetailsController.cls
public class CadenceDetailsController {

	public static String nameSpace = CadenceConstants.NAMESPACE;

	@AuraEnabled
	public static UiInputList createListForUIInput(){
		UiInputList uilObj = new UiInputList();
		uilObj.mpList = CadenceService.getPicklistValues(nameSpace+'Cadence__c', nameSpace+'matching_priority__c');
		uilObj.atList = CadenceService.getPicklistValues(nameSpace+'Cadence__c', nameSpace+'Participent_Activation__c');
		return uilObj;
	}
	public class UiInputList{
		@AuraEnabled
		public List<String> mpList;
		@AuraEnabled
		public List<String> atList;
		public UiInputList(){
			mpList = new List<String>();
			atList = new List<String>();
		}
	}
}