src/objects/Logger__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Logger</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Logger.cls
public class Logger {

    public static void create(String title, String description){
        /*
        EnableLogger__c enableLoggerSettings = [SELECT IsEnabled__c FROM EnableLogger__c LIMIT 1];
        if(enableLoggerSettings.IsEnabled__c==true){
            Logger__c loggerInstance = new Logger__c(Title__c=title, Description__c=description);
        	insert loggerInstance;
        }
		*/
        Logger__c loggerInstance = new Logger__c(Title__c=title, Description__c=description);
        insert loggerInstance;
    }
}