src/objects/Logger__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>Logger</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sequence_Logger__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Sequence Logger is used to log any errors or exceptions in the Sequence Managed Package.</description>
    <fields>
        <fullName>IsEnabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If Checked then then Sequence Managed Package will start creating logs at different application flows.</description>
        <inlineHelpText>Check to start creating logs at different application flows.</inlineHelpText>
        <label>IsEnabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Sequence Logger</label>
</CustomObject>

src/classes/LoggerTest.cls
@isTest
public class LoggerTest {
	@isTest
	public static void test_insertLog_loggerSetting_enabled(){
		Sequence_Logger__c enableLoggerSettings =new Sequence_Logger__c(IsEnabled__c=true);
		insert enableLoggerSettings;

		Logger.buildLog('Test title', 'Test description');
		Logger.insertLog();

		Logger__c logger = [Select Description__c from Logger__c];
		system.assertEquals('Test description', logger.Description__c);
	}

	public static void test_insertLog_loggerSetting_disabled(){
		Logger.buildLog('Test title', 'Test description');
		Logger.insertLog();
		Logger__c logger = [Select Description__c from Logger__c];
		system.assertEquals('', logger.Description__c);
	}
}